# -*- coding: utf-8 -*-
"""MATH376Graph.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y6GiqszC6scPVE0aBr5s-jWjEe26ogRU
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from google.colab import drive 
drive.mount('/content/gdrive')

GDP_EU =  pd.read_csv('gdrive/My Drive/EU.csv')
POP_EU = pd.read_csv('gdrive/My Drive/Population.csv')

for year in [2020,2021]:
  GDP_EU = GDP_EU.loc[GDP_EU['TIME'] != year].reset_index()

mean_gdp_df = pd.DataFrame(data=GDP_EU.groupby('LOCATION')['Value'].mean())
mean_pop_df = pd.DataFrame(data=POP_EU.groupby('LOCATION')['Value'].mean())
mean_gdp_df['percent_POP_Growth'] = mean_pop_df['Value']
mean_gdp_df.reset_index(inplace=True)
mean_gdp_df.columns = ['COUNTRY','GDP_Per_Capita', 'Percent_POP_Growth']

plt.scatter(mean_gdp_df['Percent_POP_Growth'],mean_gdp_df['GDP_Per_Capita'])
for i in range(27):
    plt.annotate(mean_gdp_df['COUNTRY'][i], (mean_gdp_df['Percent_POP_Growth'][i], mean_gdp_df['GDP_Per_Capita'][i]))


plt.title('Average_GDP_Per_Capita vs Average_Percent_POP_Growth in the EU ')
plt.xlabel('Average_Percent_POP_Growth')
plt.ylabel('Average_GDP_Per_Capita')
sns.regplot(x=mean_gdp_df['Percent_POP_Growth'], y=mean_gdp_df['GDP_Per_Capita'])
plt.savefig("GDP_vs_POP_Growth.png")

from google.colab import files
files.download("GDP_vs_POP_Growth.png")