# -*- coding: utf-8 -*-
"""MATH376.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1neKyZpW7bSgqe6nyN721Ozi5ZVeJdR_j
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from google.colab import drive 
drive.mount('/content/gdrive')

GDP_EU =  pd.read_csv('gdrive/My Drive/EU.csv')
Invest_EU = pd.read_csv('gdrive/My Drive/Investment GDP EU.csv')
GDP_Total = pd.read_csv('gdrive/My Drive/GDP Total.csv')

for year in [2020,2021]:
  GDP_EU = GDP_EU.loc[GDP_EU['TIME'] != year].reset_index()

for year in [2000,2020]:
  Invest_EU = Invest_EU.loc[Invest_EU['TIME'] != year].reset_index()

mean_EU = GDP_EU.groupby('LOCATION')['Value'].mean()
GDP_EU['percent_GDP'] = Invest_EU['Value']/GDP_Total['Value']
mean_Invest = GDP_EU.groupby('LOCATION')['percent_GDP'].mean()

mean_gdp_df = pd.DataFrame(data=mean_EU)
mean_Invest_df = pd.DataFrame(data=mean_Invest)
mean_gdp_df['percent_GDP'] = mean_Invest_df['percent_GDP']

mean_gdp_df.columns = ['COUNTRY','GDP_Per_Capita', 'Investment_Percent_GDP']
mean_gdp_df.reset_index(inplace=True)

plt.scatter(mean_gdp_df['Investment_Percent_GDP'],mean_gdp_df['GDP_Per_Capita'])
for i in range(27):
    plt.annotate(mean_gdp_df['COUNTRY'][i], (mean_gdp_df['Investment_Percent_GDP'][i], mean_gdp_df['GDP_Per_Capita'][i]))


plt.title('Average_GDP_Per_Capita vs Average_Investment_Percentage_in_GDP in the EU ')
plt.xlabel('Average_Investment_Percentage_in_GDP')
plt.ylabel('Average_GDP_Per_Capita')
plt.savefig("GDP_vs_Percent_Invest.png")

from google.colab import files
files.download("GDP_vs_Percent_Invest.png")